<a href="https://colab.research.google.com/github/christopherjneelankavil/tensorflow_basics/blob/main/TensorFlow_tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

In [2]:
zero_d_value = tf.constant(5, dtype=tf.int32)
print(zero_d_value)

tf.Tensor(5, shape=(), dtype=int32)


In [3]:
tensor_one_d = tf.constant([1,2,3,4,5])
print(tensor_one_d)

tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int32)


In [4]:
tensor_2d = tf.constant([[1,2,3],[4,5,6]])
print(tensor_2d)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [5]:
tensor_3d = tf.constant([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(tensor_3d)

tf.Tensor(
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]], shape=(2, 2, 3), dtype=int32)


In [6]:
print(tensor_3d.shape)

(2, 2, 3)


In [7]:
print(tensor_3d.ndim)

3


In [8]:
tensor_4d = tf.constant([[[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]],[[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]]])
print(tensor_4d)

tf.Tensor(
[[[[ 1  2  3]
   [ 4  5  6]]

  [[ 7  8  9]
   [10 11 12]]]


 [[[ 1  2  3]
   [ 4  5  6]]

  [[ 7  8  9]
   [10 11 12]]]], shape=(2, 2, 2, 3), dtype=int32)


In [9]:
print(tensor_4d.shape)

(2, 2, 2, 3)


In [10]:
print(tensor_4d.ndim)

4


In [11]:
import numpy as np

arr = np.array([1,2,3,4,5])

In [12]:
numpy_to_tensor = tf.convert_to_tensor(arr)
print(numpy_to_tensor)
print(numpy_to_tensor.shape)
print(numpy_to_tensor.ndim)

tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int64)
(5,)
1


In [13]:
print(arr.shape)
print(arr.ndim)

(5,)
1


In [14]:
numpy_to_tensor.dtype

tf.int64

In [15]:
tf_cast = tf.cast(numpy_to_tensor, dtype = tf.float32)
print(tf_cast)

tf.Tensor([1. 2. 3. 4. 5.], shape=(5,), dtype=float32)


In [16]:
tf_val = tf.eye(

       num_rows= 5,
       num_columns=None,
       batch_shape = [5,5],
       dtype = tf.dtypes.int32,
       name = None
)

In [17]:
print(tf_val)

tf.Tensor(
[[[[1 0 0 0 0]
   [0 1 0 0 0]
   [0 0 1 0 0]
   [0 0 0 1 0]
   [0 0 0 0 1]]

  [[1 0 0 0 0]
   [0 1 0 0 0]
   [0 0 1 0 0]
   [0 0 0 1 0]
   [0 0 0 0 1]]

  [[1 0 0 0 0]
   [0 1 0 0 0]
   [0 0 1 0 0]
   [0 0 0 1 0]
   [0 0 0 0 1]]

  [[1 0 0 0 0]
   [0 1 0 0 0]
   [0 0 1 0 0]
   [0 0 0 1 0]
   [0 0 0 0 1]]

  [[1 0 0 0 0]
   [0 1 0 0 0]
   [0 0 1 0 0]
   [0 0 0 1 0]
   [0 0 0 0 1]]]


 [[[1 0 0 0 0]
   [0 1 0 0 0]
   [0 0 1 0 0]
   [0 0 0 1 0]
   [0 0 0 0 1]]

  [[1 0 0 0 0]
   [0 1 0 0 0]
   [0 0 1 0 0]
   [0 0 0 1 0]
   [0 0 0 0 1]]

  [[1 0 0 0 0]
   [0 1 0 0 0]
   [0 0 1 0 0]
   [0 0 0 1 0]
   [0 0 0 0 1]]

  [[1 0 0 0 0]
   [0 1 0 0 0]
   [0 0 1 0 0]
   [0 0 0 1 0]
   [0 0 0 0 1]]

  [[1 0 0 0 0]
   [0 1 0 0 0]
   [0 0 1 0 0]
   [0 0 0 1 0]
   [0 0 0 0 1]]]


 [[[1 0 0 0 0]
   [0 1 0 0 0]
   [0 0 1 0 0]
   [0 0 0 1 0]
   [0 0 0 0 1]]

  [[1 0 0 0 0]
   [0 1 0 0 0]
   [0 0 1 0 0]
   [0 0 0 1 0]
   [0 0 0 0 1]]

  [[1 0 0 0 0]
   [0 1 0 0 0]
   [0 0 1 0 0]
   [0 0 0 1 0]
 

In [18]:
three_d_tensor  = tf.constant(
        [
            [
                [1,2,3],[4,5,6]
            ],
            [
                [7,8,9],[10,11,12]
            ],
            [
                [13,14,15],[16,17,18]
            ]
        ]
    )
three_d_tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [19]:
three_d_tensor[0:1, 0:1, 0:]

<tf.Tensor: shape=(1, 1, 3), dtype=int32, numpy=array([[[1, 2, 3]]], dtype=int32)>

In [20]:
## math module

In [21]:
tf.math.abs(-9)

<tf.Tensor: shape=(), dtype=int32, numpy=9>

In [22]:
x = tf.constant([50,60,70])
print(tf.math.sin(tf.cast(x, dtype=tf.float32)))

tf.Tensor([-0.26237485 -0.3048106   0.7738907 ], shape=(3,), dtype=float32)


In [23]:
val = tf.constant([3+4j])
tf.abs(val)

<tf.Tensor: shape=(1,), dtype=float64, numpy=array([5.])>

In [24]:
x = tf.constant([1,2,3])
y = tf.constant([10])
y_stretched = tf.constant([10,10,10])

print(tf.math.add(x,y) == tf.math.add(x,y_stretched))

tf.Tensor([ True  True  True], shape=(3,), dtype=bool)


In [25]:
x = tf.constant([1,2,3])
y = tf.constant([[10],[20],[30]])

print(tf.math.multiply(x,y))

tf.Tensor(
[[10 20 30]
 [20 40 60]
 [30 60 90]], shape=(3, 3), dtype=int32)


In [26]:
x = tf.constant([1,2,3])
y = tf.constant([-2,4,6])

tf.maximum(x,y)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 4, 6], dtype=int32)>

In [27]:
print(tf.math.argmax(x))

tf.Tensor(2, shape=(), dtype=int64)


In [28]:
print(tf.math.equal(x,y))

tf.Tensor([False False False], shape=(3,), dtype=bool)


In [29]:
tf.pow(tf.cast(x, dtype=tf.float32), tf.cast(y, dtype=tf.float32))

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([  1.,  16., 729.], dtype=float32)>

In [30]:
two_d = tf.constant(
    [
        [1,2,3],
        [4,5,6],
        [7,8,9]
    ]
)

In [31]:
tf.math.reduce_sum(two_d)

<tf.Tensor: shape=(), dtype=int32, numpy=45>

In [32]:
tf.math.reduce_max(two_d)

<tf.Tensor: shape=(), dtype=int32, numpy=9>

In [33]:
tf.math.reduce_min(two_d)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [34]:
tf.math.reduce_sum(two_d, axis = 0)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([12, 15, 18], dtype=int32)>

In [35]:
tf.math.reduce_sum(two_d, axis = 1)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 6, 15, 24], dtype=int32)>

#### same for max and min

In [36]:
tf.math.top_k(two_d, 2)

TopKV2(values=<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[3, 2],
       [6, 5],
       [9, 8]], dtype=int32)>, indices=<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[2, 1],
       [2, 1],
       [2, 1]], dtype=int32)>)

In [37]:
## Linear algebra

In [38]:
tf.linalg.matmul(two_d, tf.transpose(two_d))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 14,  32,  50],
       [ 32,  77, 122],
       [ 50, 122, 194]], dtype=int32)>

In [39]:
print(two_d @ tf.transpose(two_d))

tf.Tensor(
[[ 14  32  50]
 [ 32  77 122]
 [ 50 122 194]], shape=(3, 3), dtype=int32)


In [40]:
tf.linalg.matmul(
    two_d,
    two_d,
    transpose_b = True
)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 14,  32,  50],
       [ 32,  77, 122],
       [ 50, 122, 194]], dtype=int32)>

In [41]:
# band part

# (lower < 0 or m - n <= lower) and (upper < 0 or n - m <= upper)

tf.linalg.band_part(two_d, 0, -1)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [0, 5, 6],
       [0, 0, 9]], dtype=int32)>

In [42]:
print(two_d)

tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32)


In [43]:
matrix = tf.constant(
    [
        [43,7,-9],
        [587,1,1],
        [1,55,87]
    ],
    dtype = tf.float32
)

In [44]:
print(tf.linalg.inv(matrix))

tf.Tensor(
[[-4.9485352e-05  1.7072445e-03 -2.4742676e-05]
 [ 7.8972436e-02 -5.7990653e-03  8.2362182e-03]
 [-4.9924534e-02  3.6464520e-03  6.2877326e-03]], shape=(3, 3), dtype=float32)


In [45]:
matrix @ tf.linalg.inv(matrix)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 9.9999994e-01, -7.4505806e-09, -1.3969839e-09],
       [ 3.7252903e-09,  9.9999994e-01,  4.6566129e-10],
       [-1.0803342e-07, -1.8626451e-08,  1.0000000e+00]], dtype=float32)>

In [46]:
## singular value decompostions

In [47]:
s,u,v = tf.linalg.svd(matrix)

In [48]:
s

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([588.5761  , 103.00178 ,  10.666596], dtype=float32)>

In [49]:
u

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 7.3076628e-02, -3.8887016e-02,  9.9656785e-01],
       [ 9.9732417e-01,  7.5763522e-04, -7.3102511e-02],
       [ 2.0877039e-03,  9.9924332e-01,  3.8838323e-02]], dtype=float32)>

In [50]:
v

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 9.9999589e-01, -2.2151717e-03, -1.8675114e-03],
       [ 2.7586652e-03,  5.3093195e-01,  8.4740996e-01],
       [ 8.8563695e-04,  8.4741157e-01, -5.3093582e-01]], dtype=float32)>

In [51]:
## Einsum operators

In [52]:
import numpy as np

In [53]:
a = np.random.randint(0,10, size = (3,4))
b = np.random.randint(0,10, size = (4,5))

print("Normal : ")
print(np.matmul(a,b))

print("\nEinsum : ")
print(np.einsum("ij,jk -> ik",a,b))

Normal : 
[[ 35  70 121  65  97]
 [ 93 117  81 117  57]
 [ 92 134 133 128  96]]

Einsum : 
[[ 35  70 121  65  97]
 [ 93 117  81 117  57]
 [ 92 134 133 128  96]]


In [54]:
a = np.random.randint(0,9, size = (3,3))
b = np.random.randint(0,9, size = (3,3))

print(f"a : \n{a}")
print(f"b : \n{b}")

print("\nUsing a * b : ")
print(a*b)

print("\nUsing einsum")
print(np.einsum("ij,ij -> ij",a,b))

a : 
[[4 5 0]
 [7 8 7]
 [0 5 7]]
b : 
[[4 0 3]
 [6 6 4]
 [7 4 5]]

Using a * b : 
[[16  0  0]
 [42 48 28]
 [ 0 20 35]]

Using einsum
[[16  0  0]
 [42 48 28]
 [ 0 20 35]]


In [55]:
a = np.random.randint(0,10, size = (3,4))

print(a)

print(f"\nTranspose using a.T\n{a.T}")
print(f'''\nTranspose using einsum\n{np.einsum("ij->ji",a)}''')

[[8 8 8 2]
 [3 1 4 0]
 [6 6 7 2]]

Transpose using a.T
[[8 3 6]
 [8 1 6]
 [8 4 7]
 [2 0 2]]

Transpose using einsum
[[8 3 6]
 [8 1 6]
 [8 4 7]
 [2 0 2]]


In [56]:
# using 3d arrays

a = np.random.randint(0,10, size = (2,3,4))
b = np.random.randint(0,10, size = (2,4,5))


print(a.shape,b.shape)

(2, 3, 4) (2, 4, 5)


In [57]:
print(f"normal matmul : \n{np.matmul(a,b)}")
print(f'''using einsum : \n{np.einsum("bij,bjk -> bik", a, b)}''')

normal matmul : 
[[[ 96  20  70  33  56]
  [ 48  44  32  66  44]
  [108  38  52  75  50]]

 [[107  67 110 128  97]
  [108  77 102 136 123]
  [111  81 111 150 117]]]
using einsum : 
[[[ 96  20  70  33  56]
  [ 48  44  32  66  44]
  [108  38  52  75  50]]

 [[107  67 110 128  97]
  [108  77 102 136 123]
  [111  81 111 150 117]]]


In [58]:
a = np.random.randint(0,10, size = (3,3))

print(np.sum(a))

35


In [59]:
print(np.einsum("ij-> ",a))

35


In [60]:
print(np.einsum("ij -> j",a))
print(np.einsum("ij -> i",a))

[16 13  6]
[16  8 11]


In [61]:
# expand dims

In [62]:
tensor_three_d = tf.constant(
    [
        [
            [1,2,3],
            [2,3,4],
            [3,4,5]
        ],[
            [4,5,6],
            [5,6,7],
            [6,7,8]
        ],[
            [7,8,9],
            [8,9,10],
            [9,10,11]
        ]
    ]
)

In [63]:
print(tensor_three_d.shape)

(3, 3, 3)


In [64]:
print(tf.expand_dims(tensor_three_d, axis = 1).shape)

(3, 1, 3, 3)


In [65]:
# simple example
x = tf.constant([1,2,3,4])
print(f"Shape without expand dims : {x.shape}")
x_exp = tf.expand_dims(x, axis = 0)
print(f"With expand dims : {x_exp.shape}")

Shape without expand dims : (4,)
With expand dims : (1, 4)


In [66]:
# use of squeeze
x_sq = tf.squeeze(x_exp, axis = 0)
print(f"using squeeze in expanded x , final shape obtained : {x_sq.shape}")

using squeeze in expanded x , final shape obtained : (4,)


In [67]:
#use of tf.reshape

print(tf.reshape(x_sq, shape = (2,2)))
print(tf.reshape(x_sq, [2,2]))

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [68]:
#using concat

a = np.random.randint(0,10, size = (2,3))
b = np.random.randint(0,10, size = (2,3))

print(f"a : {a}\nb : {b}")

a : [[6 8 9]
 [2 1 0]]
b : [[7 2 6]
 [8 9 1]]


In [69]:
c = tf.concat([a,b], axis=0)
print(c)
print(c.shape)

tf.Tensor(
[[6 8 9]
 [2 1 0]
 [7 2 6]
 [8 9 1]], shape=(4, 3), dtype=int64)
(4, 3)


In [70]:
c = tf.concat([a,b], axis = 1)
print(c)
print(c.shape)

tf.Tensor(
[[6 8 9 7 2 6]
 [2 1 0 8 9 1]], shape=(2, 6), dtype=int64)
(2, 6)


In [71]:
#using stack

In [72]:
print(a.shape,b.shape)

(2, 3) (2, 3)


In [73]:
c = tf.stack([a,b], axis = 0)
print(c)
print(c.shape)

tf.Tensor(
[[[6 8 9]
  [2 1 0]]

 [[7 2 6]
  [8 9 1]]], shape=(2, 2, 3), dtype=int32)
(2, 2, 3)


In [74]:
c = tf.stack([a,b], axis = 1)
print(c)
print(c.shape)

tf.Tensor(
[[[6 8 9]
  [7 2 6]]

 [[2 1 0]
  [8 9 1]]], shape=(2, 2, 3), dtype=int64)
(2, 2, 3)


In [75]:
c = tf.stack([a,b], axis = 2)
print(c)
print(c.shape)

tf.Tensor(
[[[6 7]
  [8 2]
  [9 6]]

 [[2 8]
  [1 9]
  [0 1]]], shape=(2, 3, 2), dtype=int64)
(2, 3, 2)


In [76]:
# paddings

In [77]:
a = np.random.randint(0,10, size = (3,3))

In [78]:
paddings = [
    [1,1],
    [2,2]
]

tf.pad(
    a,paddings
)

<tf.Tensor: shape=(5, 7), dtype=int64, numpy=
array([[0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 5, 0, 0, 0],
       [0, 0, 6, 2, 5, 0, 0],
       [0, 0, 6, 0, 4, 0, 0],
       [0, 0, 0, 0, 0, 0, 0]])>

In [79]:
tf.pad(
    a,paddings, "CONSTANT", constant_values=1
)

<tf.Tensor: shape=(5, 7), dtype=int64, numpy=
array([[1, 1, 1, 1, 1, 1, 1],
       [1, 1, 0, 5, 0, 1, 1],
       [1, 1, 6, 2, 5, 1, 1],
       [1, 1, 6, 0, 4, 1, 1],
       [1, 1, 1, 1, 1, 1, 1]])>

In [80]:
# gather

In [81]:
params = tf.constant(['p0','p1','p2','p3','p4','p5'])
params[1:3]

<tf.Tensor: shape=(2,), dtype=string, numpy=array([b'p1', b'p2'], dtype=object)>

In [82]:
tf.gather(
    params,[1,2]
)

<tf.Tensor: shape=(2,), dtype=string, numpy=array([b'p1', b'p2'], dtype=object)>

In [83]:
tf.gather(
    params, tf.range(1,3)
)

<tf.Tensor: shape=(2,), dtype=string, numpy=array([b'p1', b'p2'], dtype=object)>

In [84]:
# use of rag tensors

In [85]:
a = np.random.randint(0,10, size = (4,3))

In [86]:
print(a)

[[0 0 6]
 [6 2 2]
 [7 4 6]
 [7 9 5]]


In [87]:
print(a.shape)

(4, 3)


In [88]:
modified_a = [
    [8, 0, 4],
    [0,],
    [2, 8, 0],
    [5, 5]
    ]

In [89]:
try :
    tensor_a = tf.constant(modified_a)
    print(modified_a.shape)
except ValueError as ve:
    print(ve)

Can't convert non-rectangular Python sequence to Tensor.


In [90]:
tensor_rag = tf.ragged.constant(modified_a)

In [91]:
print(tensor_rag)

<tf.RaggedTensor [[8, 0, 4], [0], [2, 8, 0], [5, 5]]>


In [92]:
print(tensor_rag.shape)

(4, None)


In [93]:
# ragged boolean mask

In [94]:
a = np.random.randint(0,10, size = (3,3))
a

array([[5, 9, 8],
       [3, 6, 4],
       [1, 4, 8]])

In [95]:
mask = np.random.rand(3, 3) < 0.5
mask

array([[False, False, False],
       [False, False,  True],
       [False, False,  True]])

In [96]:
tf.ragged.boolean_mask(
    a,mask
)

<tf.RaggedTensor [[], [4], [8]]>

In [97]:
# use of RaggedTensor

In [98]:
a = np.random.randint(0,10, size = (8,))

In [99]:
a

array([5, 4, 7, 2, 8, 4, 0, 6])

In [100]:
tf.RaggedTensor.from_row_lengths(
    a, row_lengths=[4,0,1,2,1]
)

<tf.RaggedTensor [[5, 4, 7, 2], [], [8], [4, 0], [6]]>

In [101]:
# sparse

In [103]:
tf_sparse = tf.sparse.SparseTensor(
    indices = [
        [1,1],
        [3,3]
    ],

    values = [1,4],
    dense_shape = [5,5]
)

In [104]:
tf_sparse

SparseTensor(indices=tf.Tensor(
[[1 1]
 [3 3]], shape=(2, 2), dtype=int64), values=tf.Tensor([1 4], shape=(2,), dtype=int32), dense_shape=tf.Tensor([5 5], shape=(2,), dtype=int64))

In [105]:
tf.sparse.to_dense(tf_sparse)

<tf.Tensor: shape=(5, 5), dtype=int32, numpy=
array([[0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 0]], dtype=int32)>

In [106]:
# string

In [107]:
tf_str = tf.constant(["hello","world"])

In [108]:
print(tf_str)

tf.Tensor([b'hello' b'world'], shape=(2,), dtype=string)


In [112]:
tf.strings.join(tf_str, separator = ' ')

<tf.Tensor: shape=(), dtype=string, numpy=b'hello world'>

In [113]:
# variables

In [114]:
x = tf.constant([1,2])

In [115]:
x_var = tf.Variable(x)
x_var

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([1, 2], dtype=int32)>

In [116]:
x_var.assign_sub([3,4])

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([-2, -2], dtype=int32)>

In [118]:
x_var.assign_add([3,3])

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([4, 4], dtype=int32)>