<a href="https://colab.research.google.com/github/christopherjneelankavil/tensorflow_basics/blob/main/TensorFlow_tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf

In [ ]:
zero_d_value = tf.constant(5, dtype=tf.int32)
print(zero_d_value)

tf.Tensor(5, shape=(), dtype=int32)


In [ ]:
tensor_one_d = tf.constant([1,2,3,4,5])
print(tensor_one_d)

tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int32)


In [ ]:
tensor_2d = tf.constant([[1,2,3],[4,5,6]])
print(tensor_2d)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [ ]:
tensor_3d = tf.constant([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(tensor_3d)

tf.Tensor(
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]], shape=(2, 2, 3), dtype=int32)


In [ ]:
print(tensor_3d.shape)

(2, 2, 3)


In [ ]:
print(tensor_3d.ndim)

3


In [ ]:
tensor_4d = tf.constant([[[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]],[[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]]])
print(tensor_4d)

tf.Tensor(
[[[[ 1  2  3]
   [ 4  5  6]]

  [[ 7  8  9]
   [10 11 12]]]


 [[[ 1  2  3]
   [ 4  5  6]]

  [[ 7  8  9]
   [10 11 12]]]], shape=(2, 2, 2, 3), dtype=int32)


In [ ]:
print(tensor_4d.shape)

(2, 2, 2, 3)


In [ ]:
print(tensor_4d.ndim)

4


In [ ]:
import numpy as np

arr = np.array([1,2,3,4,5])

In [ ]:
numpy_to_tensor = tf.convert_to_tensor(arr)
print(numpy_to_tensor)
print(numpy_to_tensor.shape)
print(numpy_to_tensor.ndim)

tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int64)
(5,)
1


In [ ]:
print(arr.shape)
print(arr.ndim)

(5,)
1


In [ ]:
numpy_to_tensor.dtype

tf.int64

In [ ]:
tf_cast = tf.cast(numpy_to_tensor, dtype = tf.float32)
print(tf_cast)

tf.Tensor([1. 2. 3. 4. 5.], shape=(5,), dtype=float32)


In [ ]:
tf_val = tf.eye(

       num_rows= 5,
       num_columns=None,
       batch_shape = [5,5],
       dtype = tf.dtypes.int32,
       name = None
)

In [ ]:
print(tf_val)

tf.Tensor(
[[[[1 0 0 0 0]
   [0 1 0 0 0]
   [0 0 1 0 0]
   [0 0 0 1 0]
   [0 0 0 0 1]]

  [[1 0 0 0 0]
   [0 1 0 0 0]
   [0 0 1 0 0]
   [0 0 0 1 0]
   [0 0 0 0 1]]

  [[1 0 0 0 0]
   [0 1 0 0 0]
   [0 0 1 0 0]
   [0 0 0 1 0]
   [0 0 0 0 1]]

  [[1 0 0 0 0]
   [0 1 0 0 0]
   [0 0 1 0 0]
   [0 0 0 1 0]
   [0 0 0 0 1]]

  [[1 0 0 0 0]
   [0 1 0 0 0]
   [0 0 1 0 0]
   [0 0 0 1 0]
   [0 0 0 0 1]]]


 [[[1 0 0 0 0]
   [0 1 0 0 0]
   [0 0 1 0 0]
   [0 0 0 1 0]
   [0 0 0 0 1]]

  [[1 0 0 0 0]
   [0 1 0 0 0]
   [0 0 1 0 0]
   [0 0 0 1 0]
   [0 0 0 0 1]]

  [[1 0 0 0 0]
   [0 1 0 0 0]
   [0 0 1 0 0]
   [0 0 0 1 0]
   [0 0 0 0 1]]

  [[1 0 0 0 0]
   [0 1 0 0 0]
   [0 0 1 0 0]
   [0 0 0 1 0]
   [0 0 0 0 1]]

  [[1 0 0 0 0]
   [0 1 0 0 0]
   [0 0 1 0 0]
   [0 0 0 1 0]
   [0 0 0 0 1]]]


 [[[1 0 0 0 0]
   [0 1 0 0 0]
   [0 0 1 0 0]
   [0 0 0 1 0]
   [0 0 0 0 1]]

  [[1 0 0 0 0]
   [0 1 0 0 0]
   [0 0 1 0 0]
   [0 0 0 1 0]
   [0 0 0 0 1]]

  [[1 0 0 0 0]
   [0 1 0 0 0]
   [0 0 1 0 0]
   [0 0 0 1 0]
 

In [ ]:
three_d_tensor  = tf.constant(
        [
            [
                [1,2,3],[4,5,6]
            ],
            [
                [7,8,9],[10,11,12]
            ],
            [
                [13,14,15],[16,17,18]
            ]
        ]
    )
three_d_tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [ ]:
three_d_tensor[0:1, 0:1, 0:]

<tf.Tensor: shape=(1, 1, 3), dtype=int32, numpy=array([[[1, 2, 3]]], dtype=int32)>

In [ ]:
## math module

In [ ]:
tf.math.abs(-9)

<tf.Tensor: shape=(), dtype=int32, numpy=9>

In [ ]:
x = tf.constant([50,60,70])
print(tf.math.sin(tf.cast(x, dtype=tf.float32)))

tf.Tensor([-0.26237485 -0.3048106   0.7738907 ], shape=(3,), dtype=float32)


In [ ]:
val = tf.constant([3+4j])
tf.abs(val)

<tf.Tensor: shape=(1,), dtype=float64, numpy=array([5.])>

In [ ]:
x = tf.constant([1,2,3])
y = tf.constant([10])
y_stretched = tf.constant([10,10,10])

print(tf.math.add(x,y) == tf.math.add(x,y_stretched))

tf.Tensor([ True  True  True], shape=(3,), dtype=bool)


In [ ]:
x = tf.constant([1,2,3])
y = tf.constant([[10],[20],[30]])

print(tf.math.multiply(x,y))

tf.Tensor(
[[10 20 30]
 [20 40 60]
 [30 60 90]], shape=(3, 3), dtype=int32)


In [ ]:
x = tf.constant([1,2,3])
y = tf.constant([-2,4,6])

tf.maximum(x,y)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 4, 6], dtype=int32)>

In [ ]:
print(tf.math.argmax(x))

tf.Tensor(2, shape=(), dtype=int64)


In [ ]:
print(tf.math.equal(x,y))

tf.Tensor([False False False], shape=(3,), dtype=bool)


In [ ]:
tf.pow(tf.cast(x, dtype=tf.float32), tf.cast(y, dtype=tf.float32))

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([  1.,  16., 729.], dtype=float32)>

In [ ]:
two_d = tf.constant(
    [
        [1,2,3],
        [4,5,6],
        [7,8,9]
    ]
)

In [ ]:
tf.math.reduce_sum(two_d)

<tf.Tensor: shape=(), dtype=int32, numpy=45>

In [ ]:
tf.math.reduce_max(two_d)

<tf.Tensor: shape=(), dtype=int32, numpy=9>

In [ ]:
tf.math.reduce_min(two_d)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [ ]:
tf.math.reduce_sum(two_d, axis = 0)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([12, 15, 18], dtype=int32)>

In [ ]:
tf.math.reduce_sum(two_d, axis = 1)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 6, 15, 24], dtype=int32)>

#### same for max and min

In [ ]:
tf.math.top_k(two_d, 2)

TopKV2(values=<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[3, 2],
       [6, 5],
       [9, 8]], dtype=int32)>, indices=<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[2, 1],
       [2, 1],
       [2, 1]], dtype=int32)>)

In [ ]:
## Linear algebra

In [ ]:
tf.linalg.matmul(two_d, tf.transpose(two_d))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 14,  32,  50],
       [ 32,  77, 122],
       [ 50, 122, 194]], dtype=int32)>

In [ ]:
print(two_d @ tf.transpose(two_d))

tf.Tensor(
[[ 14  32  50]
 [ 32  77 122]
 [ 50 122 194]], shape=(3, 3), dtype=int32)


In [ ]:
tf.linalg.matmul(
    two_d,
    two_d,
    transpose_b = True
)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 14,  32,  50],
       [ 32,  77, 122],
       [ 50, 122, 194]], dtype=int32)>

In [ ]:
# band part

# (lower < 0 or m - n <= lower) and (upper < 0 or n - m <= upper)

tf.linalg.band_part(two_d, 0, -1)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [0, 5, 6],
       [0, 0, 9]], dtype=int32)>

In [ ]:
print(two_d)

tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32)


In [ ]:
matrix = tf.constant(
    [
        [43,7,-9],
        [587,1,1],
        [1,55,87]
    ],
    dtype = tf.float32
)

In [ ]:
print(tf.linalg.inv(matrix))

tf.Tensor(
[[-4.9485352e-05  1.7072445e-03 -2.4742676e-05]
 [ 7.8972436e-02 -5.7990653e-03  8.2362182e-03]
 [-4.9924534e-02  3.6464520e-03  6.2877326e-03]], shape=(3, 3), dtype=float32)


In [ ]:
matrix @ tf.linalg.inv(matrix)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 9.9999994e-01, -7.4505806e-09, -1.3969839e-09],
       [ 3.7252903e-09,  9.9999994e-01,  4.6566129e-10],
       [-1.0803342e-07, -1.8626451e-08,  1.0000000e+00]], dtype=float32)>

In [ ]:
## singular value decompostions

In [ ]:
s,u,v = tf.linalg.svd(matrix)

In [ ]:
s

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([588.5761  , 103.00178 ,  10.666596], dtype=float32)>

In [ ]:
u

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 7.3076628e-02, -3.8887016e-02,  9.9656785e-01],
       [ 9.9732417e-01,  7.5763522e-04, -7.3102511e-02],
       [ 2.0877039e-03,  9.9924332e-01,  3.8838323e-02]], dtype=float32)>

In [ ]:
v

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 9.9999589e-01, -2.2151717e-03, -1.8675114e-03],
       [ 2.7586652e-03,  5.3093195e-01,  8.4740996e-01],
       [ 8.8563695e-04,  8.4741157e-01, -5.3093582e-01]], dtype=float32)>

In [1]:
## Einsum operators

In [2]:
import numpy as np

In [5]:
a = np.random.randint(0,10, size = (3,4))
b = np.random.randint(0,10, size = (4,5))

print("Normal : ")
print(np.matmul(a,b))

print("\nEinsum : ")
print(np.einsum("ij,jk -> ik",a,b))

Normal : 
[[ 89  56  41  97  72]
 [ 88  62  81  69  50]
 [ 95  58  62 115  58]]

Einsum : 
[[ 89  56  41  97  72]
 [ 88  62  81  69  50]
 [ 95  58  62 115  58]]


In [11]:
a = np.random.randint(0,9, size = (3,3))
b = np.random.randint(0,9, size = (3,3))

print(f"a : \n{a}")
print(f"b : \n{b}")

print("\nUsing a * b : ")
print(a*b)

print("\nUsing einsum")
print(np.einsum("ij,ij -> ij",a,b))

a : 
[[3 6 4]
 [7 4 0]
 [6 6 5]]
b : 
[[5 7 0]
 [6 3 5]
 [5 1 8]]

Using a * b : 
[[15 42  0]
 [42 12  0]
 [30  6 40]]

Using einsum
[[15 42  0]
 [42 12  0]
 [30  6 40]]


In [13]:
a = np.random.randint(0,10, size = (3,4))

print(a)

print(f"\nTranspose using a.T\n{a.T}")
print(f'''\nTranspose using einsum\n{np.einsum("ij->ji",a)}''')

[[9 9 9 7]
 [1 6 1 9]
 [0 0 5 7]]

Transpose using a.T
[[9 1 0]
 [9 6 0]
 [9 1 5]
 [7 9 7]]

Transpose using einsum
[[9 1 0]
 [9 6 0]
 [9 1 5]
 [7 9 7]]


In [14]:
# using 3d arrays

a = np.random.randint(0,10, size = (2,3,4))
b = np.random.randint(0,10, size = (2,4,5))


print(a.shape,b.shape)

(2, 3, 4) (2, 4, 5)


In [18]:
print(f"normal matmul : \n{np.matmul(a,b)}")
print(f'''using einsum : \n{np.einsum("bij,bjk -> bik", a, b)}''')

normal matmul : 
[[[ 22  31  12  36  17]
  [ 96 150  53 113  74]
  [ 21  48  21  75  24]]

 [[ 31  75  55 110  87]
  [ 44 101  93  82  75]
  [ 25  59  44  50  46]]]
using einsum : 
[[[ 22  31  12  36  17]
  [ 96 150  53 113  74]
  [ 21  48  21  75  24]]

 [[ 31  75  55 110  87]
  [ 44 101  93  82  75]
  [ 25  59  44  50  46]]]


In [19]:
a = np.random.randint(0,10, size = (3,3))

print(np.sum(a))

28


In [21]:
print(np.einsum("ij-> ",a))

28


In [22]:
print(np.einsum("ij -> j",a))
print(np.einsum("ij -> i",a))

[14  5  9]
[12 11  5]
