<a href="https://colab.research.google.com/github/christopherjneelankavil/tensorflow_basics/blob/main/TensorFlow_tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf

In [ ]:
zero_d_value = tf.constant(5, dtype=tf.int32)
print(zero_d_value)

tf.Tensor(5, shape=(), dtype=int32)


In [ ]:
tensor_one_d = tf.constant([1,2,3,4,5])
print(tensor_one_d)

tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int32)


In [ ]:
tensor_2d = tf.constant([[1,2,3],[4,5,6]])
print(tensor_2d)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [ ]:
tensor_3d = tf.constant([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(tensor_3d)

tf.Tensor(
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]], shape=(2, 2, 3), dtype=int32)


In [ ]:
print(tensor_3d.shape)

(2, 2, 3)


In [ ]:
print(tensor_3d.ndim)

3


In [ ]:
tensor_4d = tf.constant([[[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]],[[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]]])
print(tensor_4d)

tf.Tensor(
[[[[ 1  2  3]
   [ 4  5  6]]

  [[ 7  8  9]
   [10 11 12]]]


 [[[ 1  2  3]
   [ 4  5  6]]

  [[ 7  8  9]
   [10 11 12]]]], shape=(2, 2, 2, 3), dtype=int32)


In [ ]:
print(tensor_4d.shape)

(2, 2, 2, 3)


In [ ]:
print(tensor_4d.ndim)

4


In [ ]:
import numpy as np

arr = np.array([1,2,3,4,5])

In [ ]:
numpy_to_tensor = tf.convert_to_tensor(arr)
print(numpy_to_tensor)
print(numpy_to_tensor.shape)
print(numpy_to_tensor.ndim)

tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int64)
(5,)
1


In [ ]:
print(arr.shape)
print(arr.ndim)

(5,)
1


In [ ]:
numpy_to_tensor.dtype

tf.int64

In [ ]:
tf_cast = tf.cast(numpy_to_tensor, dtype = tf.float32)
print(tf_cast)

tf.Tensor([1. 2. 3. 4. 5.], shape=(5,), dtype=float32)


In [ ]:
tf_val = tf.eye(

       num_rows= 5,
       num_columns=None,
       batch_shape = [5,5],
       dtype = tf.dtypes.int32,
       name = None
)

In [ ]:
print(tf_val)

tf.Tensor(
[[[[1 0 0 0 0]
   [0 1 0 0 0]
   [0 0 1 0 0]
   [0 0 0 1 0]
   [0 0 0 0 1]]

  [[1 0 0 0 0]
   [0 1 0 0 0]
   [0 0 1 0 0]
   [0 0 0 1 0]
   [0 0 0 0 1]]

  [[1 0 0 0 0]
   [0 1 0 0 0]
   [0 0 1 0 0]
   [0 0 0 1 0]
   [0 0 0 0 1]]

  [[1 0 0 0 0]
   [0 1 0 0 0]
   [0 0 1 0 0]
   [0 0 0 1 0]
   [0 0 0 0 1]]

  [[1 0 0 0 0]
   [0 1 0 0 0]
   [0 0 1 0 0]
   [0 0 0 1 0]
   [0 0 0 0 1]]]


 [[[1 0 0 0 0]
   [0 1 0 0 0]
   [0 0 1 0 0]
   [0 0 0 1 0]
   [0 0 0 0 1]]

  [[1 0 0 0 0]
   [0 1 0 0 0]
   [0 0 1 0 0]
   [0 0 0 1 0]
   [0 0 0 0 1]]

  [[1 0 0 0 0]
   [0 1 0 0 0]
   [0 0 1 0 0]
   [0 0 0 1 0]
   [0 0 0 0 1]]

  [[1 0 0 0 0]
   [0 1 0 0 0]
   [0 0 1 0 0]
   [0 0 0 1 0]
   [0 0 0 0 1]]

  [[1 0 0 0 0]
   [0 1 0 0 0]
   [0 0 1 0 0]
   [0 0 0 1 0]
   [0 0 0 0 1]]]


 [[[1 0 0 0 0]
   [0 1 0 0 0]
   [0 0 1 0 0]
   [0 0 0 1 0]
   [0 0 0 0 1]]

  [[1 0 0 0 0]
   [0 1 0 0 0]
   [0 0 1 0 0]
   [0 0 0 1 0]
   [0 0 0 0 1]]

  [[1 0 0 0 0]
   [0 1 0 0 0]
   [0 0 1 0 0]
   [0 0 0 1 0]
 

In [ ]:
three_d_tensor  = tf.constant(
        [
            [
                [1,2,3],[4,5,6]
            ],
            [
                [7,8,9],[10,11,12]
            ],
            [
                [13,14,15],[16,17,18]
            ]
        ]
    )
three_d_tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [ ]:
three_d_tensor[0:1, 0:1, 0:]

<tf.Tensor: shape=(1, 1, 3), dtype=int32, numpy=array([[[1, 2, 3]]], dtype=int32)>

In [ ]:
## math module

In [ ]:
tf.math.abs(-9)

<tf.Tensor: shape=(), dtype=int32, numpy=9>

In [ ]:
x = tf.constant([50,60,70])
print(tf.math.sin(tf.cast(x, dtype=tf.float32)))

tf.Tensor([-0.26237485 -0.3048106   0.7738907 ], shape=(3,), dtype=float32)


In [ ]:
val = tf.constant([3+4j])
tf.abs(val)

<tf.Tensor: shape=(1,), dtype=float64, numpy=array([5.])>

In [ ]:
x = tf.constant([1,2,3])
y = tf.constant([10])
y_stretched = tf.constant([10,10,10])

print(tf.math.add(x,y) == tf.math.add(x,y_stretched))

tf.Tensor([ True  True  True], shape=(3,), dtype=bool)


In [ ]:
x = tf.constant([1,2,3])
y = tf.constant([[10],[20],[30]])

print(tf.math.multiply(x,y))

tf.Tensor(
[[10 20 30]
 [20 40 60]
 [30 60 90]], shape=(3, 3), dtype=int32)


In [ ]:
x = tf.constant([1,2,3])
y = tf.constant([-2,4,6])

tf.maximum(x,y)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 4, 6], dtype=int32)>

In [ ]:
print(tf.math.argmax(x))

tf.Tensor(2, shape=(), dtype=int64)
