<a href="https://colab.research.google.com/github/christopherjneelankavil/tensorflow_basics/blob/main/TensorFlow_tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import tensorflow as tf

In [3]:
zero_d_value = tf.constant(5, dtype=tf.int32)
print(zero_d_value)

tf.Tensor(5, shape=(), dtype=int32)


In [4]:
tensor_one_d = tf.constant([1,2,3,4,5])
print(tensor_one_d)

tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int32)


In [5]:
tensor_2d = tf.constant([[1,2,3],[4,5,6]])
print(tensor_2d)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [6]:
tensor_3d = tf.constant([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(tensor_3d)

tf.Tensor(
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]], shape=(2, 2, 3), dtype=int32)


In [7]:
print(tensor_3d.shape)

(2, 2, 3)


In [8]:
print(tensor_3d.ndim)

3


In [9]:
tensor_4d = tf.constant([[[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]],[[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]]])
print(tensor_4d)

tf.Tensor(
[[[[ 1  2  3]
   [ 4  5  6]]

  [[ 7  8  9]
   [10 11 12]]]


 [[[ 1  2  3]
   [ 4  5  6]]

  [[ 7  8  9]
   [10 11 12]]]], shape=(2, 2, 2, 3), dtype=int32)


In [10]:
print(tensor_4d.shape)

(2, 2, 2, 3)


In [11]:
print(tensor_4d.ndim)

4


In [12]:
import numpy as np

arr = np.array([1,2,3,4,5])

In [13]:
numpy_to_tensor = tf.convert_to_tensor(arr)
print(numpy_to_tensor)
print(numpy_to_tensor.shape)
print(numpy_to_tensor.ndim)

tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int64)
(5,)
1


In [14]:
print(arr.shape)
print(arr.ndim)

(5,)
1


In [15]:
numpy_to_tensor.dtype

tf.int64

In [16]:
tf_cast = tf.cast(numpy_to_tensor, dtype = tf.float32)
print(tf_cast)

tf.Tensor([1. 2. 3. 4. 5.], shape=(5,), dtype=float32)


In [17]:
tf_val = tf.eye(

       num_rows= 5,
       num_columns=None,
       batch_shape = [5,5],
       dtype = tf.dtypes.int32,
       name = None
)

In [18]:
print(tf_val)

tf.Tensor(
[[[[1 0 0 0 0]
   [0 1 0 0 0]
   [0 0 1 0 0]
   [0 0 0 1 0]
   [0 0 0 0 1]]

  [[1 0 0 0 0]
   [0 1 0 0 0]
   [0 0 1 0 0]
   [0 0 0 1 0]
   [0 0 0 0 1]]

  [[1 0 0 0 0]
   [0 1 0 0 0]
   [0 0 1 0 0]
   [0 0 0 1 0]
   [0 0 0 0 1]]

  [[1 0 0 0 0]
   [0 1 0 0 0]
   [0 0 1 0 0]
   [0 0 0 1 0]
   [0 0 0 0 1]]

  [[1 0 0 0 0]
   [0 1 0 0 0]
   [0 0 1 0 0]
   [0 0 0 1 0]
   [0 0 0 0 1]]]


 [[[1 0 0 0 0]
   [0 1 0 0 0]
   [0 0 1 0 0]
   [0 0 0 1 0]
   [0 0 0 0 1]]

  [[1 0 0 0 0]
   [0 1 0 0 0]
   [0 0 1 0 0]
   [0 0 0 1 0]
   [0 0 0 0 1]]

  [[1 0 0 0 0]
   [0 1 0 0 0]
   [0 0 1 0 0]
   [0 0 0 1 0]
   [0 0 0 0 1]]

  [[1 0 0 0 0]
   [0 1 0 0 0]
   [0 0 1 0 0]
   [0 0 0 1 0]
   [0 0 0 0 1]]

  [[1 0 0 0 0]
   [0 1 0 0 0]
   [0 0 1 0 0]
   [0 0 0 1 0]
   [0 0 0 0 1]]]


 [[[1 0 0 0 0]
   [0 1 0 0 0]
   [0 0 1 0 0]
   [0 0 0 1 0]
   [0 0 0 0 1]]

  [[1 0 0 0 0]
   [0 1 0 0 0]
   [0 0 1 0 0]
   [0 0 0 1 0]
   [0 0 0 0 1]]

  [[1 0 0 0 0]
   [0 1 0 0 0]
   [0 0 1 0 0]
   [0 0 0 1 0]
 

In [19]:
three_d_tensor  = tf.constant(
        [
            [
                [1,2,3],[4,5,6]
            ],
            [
                [7,8,9],[10,11,12]
            ],
            [
                [13,14,15],[16,17,18]
            ]
        ]
    )
three_d_tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [20]:
three_d_tensor[0:1, 0:1, 0:]

<tf.Tensor: shape=(1, 1, 3), dtype=int32, numpy=array([[[1, 2, 3]]], dtype=int32)>

In [21]:
## math module

In [22]:
tf.math.abs(-9)

<tf.Tensor: shape=(), dtype=int32, numpy=9>

In [23]:
x = tf.constant([50,60,70])
print(tf.math.sin(tf.cast(x, dtype=tf.float32)))

tf.Tensor([-0.26237485 -0.3048106   0.7738907 ], shape=(3,), dtype=float32)


In [24]:
val = tf.constant([3+4j])
tf.abs(val)

<tf.Tensor: shape=(1,), dtype=float64, numpy=array([5.])>

In [25]:
x = tf.constant([1,2,3])
y = tf.constant([10])
y_stretched = tf.constant([10,10,10])

print(tf.math.add(x,y) == tf.math.add(x,y_stretched))

tf.Tensor([ True  True  True], shape=(3,), dtype=bool)


In [26]:
x = tf.constant([1,2,3])
y = tf.constant([[10],[20],[30]])

print(tf.math.multiply(x,y))

tf.Tensor(
[[10 20 30]
 [20 40 60]
 [30 60 90]], shape=(3, 3), dtype=int32)


In [27]:
x = tf.constant([1,2,3])
y = tf.constant([-2,4,6])

tf.maximum(x,y)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 4, 6], dtype=int32)>

In [28]:
print(tf.math.argmax(x))

tf.Tensor(2, shape=(), dtype=int64)


In [29]:
print(tf.math.equal(x,y))

tf.Tensor([False False False], shape=(3,), dtype=bool)


In [30]:
tf.pow(tf.cast(x, dtype=tf.float32), tf.cast(y, dtype=tf.float32))

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([  1.,  16., 729.], dtype=float32)>

In [31]:
two_d = tf.constant(
    [
        [1,2,3],
        [4,5,6],
        [7,8,9]
    ]
)

In [32]:
tf.math.reduce_sum(two_d)

<tf.Tensor: shape=(), dtype=int32, numpy=45>

In [33]:
tf.math.reduce_max(two_d)

<tf.Tensor: shape=(), dtype=int32, numpy=9>

In [34]:
tf.math.reduce_min(two_d)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [35]:
tf.math.reduce_sum(two_d, axis = 0)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([12, 15, 18], dtype=int32)>

In [36]:
tf.math.reduce_sum(two_d, axis = 1)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 6, 15, 24], dtype=int32)>

#### same for max and min

In [37]:
tf.math.top_k(two_d, 2)

TopKV2(values=<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[3, 2],
       [6, 5],
       [9, 8]], dtype=int32)>, indices=<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[2, 1],
       [2, 1],
       [2, 1]], dtype=int32)>)

In [38]:
## Linear algebra

In [39]:
tf.linalg.matmul(two_d, tf.transpose(two_d))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 14,  32,  50],
       [ 32,  77, 122],
       [ 50, 122, 194]], dtype=int32)>

In [40]:
print(two_d @ tf.transpose(two_d))

tf.Tensor(
[[ 14  32  50]
 [ 32  77 122]
 [ 50 122 194]], shape=(3, 3), dtype=int32)


In [41]:
tf.linalg.matmul(
    two_d,
    two_d,
    transpose_b = True
)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 14,  32,  50],
       [ 32,  77, 122],
       [ 50, 122, 194]], dtype=int32)>

In [42]:
# band part

# (lower < 0 or m - n <= lower) and (upper < 0 or n - m <= upper)

tf.linalg.band_part(two_d, 0, -1)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [0, 5, 6],
       [0, 0, 9]], dtype=int32)>

In [43]:
print(two_d)

tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32)


In [44]:
matrix = tf.constant(
    [
        [43,7,-9],
        [587,1,1],
        [1,55,87]
    ],
    dtype = tf.float32
)

In [45]:
print(tf.linalg.inv(matrix))

tf.Tensor(
[[-4.9485352e-05  1.7072445e-03 -2.4742676e-05]
 [ 7.8972436e-02 -5.7990653e-03  8.2362182e-03]
 [-4.9924534e-02  3.6464520e-03  6.2877326e-03]], shape=(3, 3), dtype=float32)


In [46]:
matrix @ tf.linalg.inv(matrix)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 9.9999994e-01, -7.4505806e-09, -1.3969839e-09],
       [ 3.7252903e-09,  9.9999994e-01,  4.6566129e-10],
       [-1.0803342e-07, -1.8626451e-08,  1.0000000e+00]], dtype=float32)>

In [47]:
## singular value decompostions

In [48]:
s,u,v = tf.linalg.svd(matrix)

In [49]:
s

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([588.5761  , 103.00178 ,  10.666596], dtype=float32)>

In [50]:
u

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 7.3076628e-02, -3.8887016e-02,  9.9656785e-01],
       [ 9.9732417e-01,  7.5763522e-04, -7.3102511e-02],
       [ 2.0877039e-03,  9.9924332e-01,  3.8838323e-02]], dtype=float32)>

In [51]:
v

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 9.9999589e-01, -2.2151717e-03, -1.8675114e-03],
       [ 2.7586652e-03,  5.3093195e-01,  8.4740996e-01],
       [ 8.8563695e-04,  8.4741157e-01, -5.3093582e-01]], dtype=float32)>

In [52]:
## Einsum operators

In [53]:
import numpy as np

In [54]:
a = np.random.randint(0,10, size = (3,4))
b = np.random.randint(0,10, size = (4,5))

print("Normal : ")
print(np.matmul(a,b))

print("\nEinsum : ")
print(np.einsum("ij,jk -> ik",a,b))

Normal : 
[[ 52  44  83  62  59]
 [115  44  76 106 115]
 [ 32  56  57  26  43]]

Einsum : 
[[ 52  44  83  62  59]
 [115  44  76 106 115]
 [ 32  56  57  26  43]]


In [55]:
a = np.random.randint(0,9, size = (3,3))
b = np.random.randint(0,9, size = (3,3))

print(f"a : \n{a}")
print(f"b : \n{b}")

print("\nUsing a * b : ")
print(a*b)

print("\nUsing einsum")
print(np.einsum("ij,ij -> ij",a,b))

a : 
[[7 8 1]
 [4 7 0]
 [0 2 6]]
b : 
[[2 3 8]
 [1 8 2]
 [0 7 8]]

Using a * b : 
[[14 24  8]
 [ 4 56  0]
 [ 0 14 48]]

Using einsum
[[14 24  8]
 [ 4 56  0]
 [ 0 14 48]]


In [56]:
a = np.random.randint(0,10, size = (3,4))

print(a)

print(f"\nTranspose using a.T\n{a.T}")
print(f'''\nTranspose using einsum\n{np.einsum("ij->ji",a)}''')

[[5 4 1 5]
 [9 2 0 3]
 [9 1 6 6]]

Transpose using a.T
[[5 9 9]
 [4 2 1]
 [1 0 6]
 [5 3 6]]

Transpose using einsum
[[5 9 9]
 [4 2 1]
 [1 0 6]
 [5 3 6]]


In [57]:
# using 3d arrays

a = np.random.randint(0,10, size = (2,3,4))
b = np.random.randint(0,10, size = (2,4,5))


print(a.shape,b.shape)

(2, 3, 4) (2, 4, 5)


In [58]:
print(f"normal matmul : \n{np.matmul(a,b)}")
print(f'''using einsum : \n{np.einsum("bij,bjk -> bik", a, b)}''')

normal matmul : 
[[[ 72 135 109 107  80]
  [ 98 149 148 139  82]
  [ 48  68  70  70  39]]

 [[106 114 172  64 106]
  [138 129 177  66 114]
  [116  88 114  32  78]]]
using einsum : 
[[[ 72 135 109 107  80]
  [ 98 149 148 139  82]
  [ 48  68  70  70  39]]

 [[106 114 172  64 106]
  [138 129 177  66 114]
  [116  88 114  32  78]]]


In [59]:
a = np.random.randint(0,10, size = (3,3))

print(np.sum(a))

51


In [60]:
print(np.einsum("ij-> ",a))

51


In [61]:
print(np.einsum("ij -> j",a))
print(np.einsum("ij -> i",a))

[ 9 17 25]
[24 12 15]


In [62]:
# expand dims

In [63]:
tensor_three_d = tf.constant(
    [
        [
            [1,2,3],
            [2,3,4],
            [3,4,5]
        ],[
            [4,5,6],
            [5,6,7],
            [6,7,8]
        ],[
            [7,8,9],
            [8,9,10],
            [9,10,11]
        ]
    ]
)

In [64]:
print(tensor_three_d.shape)

(3, 3, 3)


In [66]:
print(tf.expand_dims(tensor_three_d, axis = 1).shape)

(3, 1, 3, 3)


In [68]:
# simple example
x = tf.constant([1,2,3,4])
print(f"Shape without expand dims : {x.shape}")
x_exp = tf.expand_dims(x, axis = 0)
print(f"With expand dims : {x_exp.shape}")

Shape without expand dims : (4,)
With expand dims : (1, 4)


In [70]:
# use of squeeze

print(f"using squeeze in expanded x , final shape obtained : {tf.squeeze(x_exp, axis = 0).shape}")

using squeeze in expanded x , final shape obtained : (4,)
